#!/bin/bash
# ===========================================
# Generate PgBouncer userlist.txt from environment
# ===========================================
# Usage: ./generate-pgbouncer-userlist.sh
# 
# This script generates the userlist.txt file for PgBouncer
# using credentials from .env.production
#
# Run this before starting PgBouncer in production

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
ENV_FILE="$PROJECT_ROOT/.env.production"
OUTPUT_FILE="$SCRIPT_DIR/pgbouncer-userlist.txt"

# Load environment variables
if [ -f "$ENV_FILE" ]; then
    export $(grep -v '^#' "$ENV_FILE" | xargs)
else
    echo "❌ Error: $ENV_FILE not found"
    exit 1
fi

# Check required variables
if [ -z "$POSTGRES_USER" ] || [ -z "$POSTGRES_PASSWORD" ]; then
    echo "❌ Error: POSTGRES_USER and POSTGRES_PASSWORD must be set in $ENV_FILE"
    exit 1
fi

# Generate userlist.txt
cat > "$OUTPUT_FILE" << EOF
# PgBouncer userlist.txt
# Auto-generated by generate-pgbouncer-userlist.sh
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# WARNING: This file contains credentials. Keep it secure!

"$POSTGRES_USER" "$POSTGRES_PASSWORD"
EOF

chmod 600 "$OUTPUT_FILE"

echo "✅ Generated $OUTPUT_FILE"
echo "   User: $POSTGRES_USER"
echo "   Password: ****"
