/**
 * Telegram Echo Bot — JavaScript starter template.
 *
 * The simplest possible Telegram plugin: replies to every incoming
 * text message with a configurable greeting + the original text.
 * Used as the canonical Wave 2 happy-path template and the smoke
 * test for the codegen pipeline.
 *
 * @module modules/cursor/buildspec/templates/telegram-echo-javascript
 */

import { z } from "zod";

import type {
    CodeTemplate,
    RenderedManifest,
    TemplateRenderArgs,
    TemplateRenderResult,
} from "./types";

const inputs = z.object({
  /** Prepended to the echoed text; supports basic emojis. */
  greeting: z.string().min(1).max(120).default("👋"),
  /**
   * If `true`, the bot also echoes when invoked via inline mention
   * (e.g. group chats). Defaults to `false` to stay quiet by default.
   */
  respondInGroups: z.boolean().default(false),
});

type EchoInputs = z.infer<typeof inputs>;

function renderManifest(
  args: TemplateRenderArgs<EchoInputs>,
): RenderedManifest {
  return {
    slug: args.slug,
    name: args.name,
    version: "1.0.0",
    description:
      args.description ??
      "Echoes incoming Telegram messages with a configurable greeting.",
    category: "messaging",
    requiredGateways: ["TELEGRAM_BOT"],
    tags: ["telegram", "echo", "starter"],
    difficulty: "beginner",
    configSchema: {
      type: "object",
      properties: {
        greeting: {
          type: "string",
          title: "Greeting",
          description: "Prefix prepended to every echoed message.",
          default: args.inputs.greeting,
        },
        respondInGroups: {
          type: "boolean",
          title: "Respond in groups",
          default: args.inputs.respondInGroups,
        },
      },
      required: ["greeting"],
    },
    entryFile: "index.js",
    layout: "directory",
    icon: "send",
    author: "cursor-buildspec",
    isBuiltin: false,
    eventTypes: ["telegram.message"],
    eventRole: "responder",
    inputSchema: null,
    outputSchema: null,
  };
}

function renderEntry(args: TemplateRenderArgs<EchoInputs>): string {
  // Keep this code dependency-free so it deploys without an `npm install`
  // step inside the workspace container. The host injects `ctx` with a
  // `send(text)` helper bound to the gateway's send-message API.
  const greeting = JSON.stringify(args.inputs.greeting);
  const respondInGroups = args.inputs.respondInGroups ? "true" : "false";

  return `// Auto-generated by cursor-buildspec template "telegram-echo-javascript".
// Plugin: ${args.slug}
//
// Hook signature: \`onMessage(event, ctx)\` where:
//   event.text       — the incoming message text
//   event.chat.type  — "private" | "group" | "supergroup" | "channel"
//   ctx.config       — your saved configuration (see plugin.json)
//   ctx.send(text)   — reply via the bound Telegram gateway
//
// Edit freely — this file is the source of truth once generated.

const DEFAULT_GREETING = ${greeting};
const RESPOND_IN_GROUPS = ${respondInGroups};

module.exports.onMessage = async function onMessage(event, ctx) {
  const text = (event && typeof event.text === "string") ? event.text : "";
  if (!text) return;

  const chatType = event && event.chat ? event.chat.type : "private";
  const isGroup = chatType === "group" || chatType === "supergroup";
  if (isGroup && !(ctx.config && ctx.config.respondInGroups) && !RESPOND_IN_GROUPS) {
    return;
  }

  const greeting = (ctx.config && typeof ctx.config.greeting === "string" && ctx.config.greeting.length > 0)
    ? ctx.config.greeting
    : DEFAULT_GREETING;

  await ctx.send(\`\${greeting} \${text}\`);
};
`;
}

function renderReadme(args: TemplateRenderArgs<EchoInputs>): string {
  return `# ${args.name}

Auto-generated Telegram echo bot.

**Slug:** \`${args.slug}\`

## What it does

Replies to every incoming text message with a configurable greeting
followed by the original message text.

## Configuration

| Field             | Type    | Default            | Description                                |
| ----------------- | ------- | ------------------ | ------------------------------------------ |
| \`greeting\`        | string  | \`${args.inputs.greeting}\` | Prefix prepended to every echoed message. |
| \`respondInGroups\` | boolean | \`${args.inputs.respondInGroups}\` | Reply in group chats too.                  |

## Files

- \`plugin.json\` — manifest
- \`index.js\` — entry point (\`onMessage\` hook)
- \`README.md\` — this file

## Generated by

cursor-buildspec template \`telegram-echo-javascript\` v1.
`;
}

export const telegramEchoJavascriptTemplate: CodeTemplate<EchoInputs> = {
  id: "telegram-echo-javascript",
  displayName: "Telegram Echo (JavaScript)",
  description:
    "Replies to incoming Telegram messages with a configurable greeting. Zero dependencies.",
  language: "javascript",
  requiredGateways: ["TELEGRAM_BOT"],
  inputs,
  render(args: TemplateRenderArgs<EchoInputs>): TemplateRenderResult {
    const manifest = renderManifest(args);
    const indexJs = renderEntry(args);
    const readme = renderReadme(args);

    return {
      manifest,
      slug: args.slug,
      entryFile: manifest.entryFile,
      files: [
        { path: "plugin.json", content: JSON.stringify(manifest, null, 2) + "\n" },
        { path: "index.js", content: indexJs },
        { path: "README.md", content: readme },
      ],
    };
  },
};
