/**
 * Webhook Handler — JavaScript starter template.
 *
 * Generates a plugin that handles incoming HTTP_ROUTE events. Useful
 * pair with `BuildSpec.resources[].kind = "HTTP_ROUTE"` whose
 * `targetPluginRef` points at this generated plugin.
 *
 * Gateway-agnostic — does not require any messaging gateway.
 *
 * @module modules/cursor/buildspec/templates/webhook-handler-javascript
 */

import { z } from "zod";

import type {
    CodeTemplate,
    RenderedManifest,
    TemplateRenderArgs,
    TemplateRenderResult,
} from "./types";

const inputs = z.object({
  /**
   * Default JSON body returned on success when the user code does not
   * explicitly call `ctx.respond(...)`.
   */
  defaultResponse: z
    .record(z.string(), z.unknown())
    .default({ ok: true }),
  /**
   * If true, log each incoming request payload at info level. Defaults
   * to false so generated plugins are quiet by default.
   */
  logRequests: z.boolean().default(false),
});

type WebhookInputs = z.infer<typeof inputs>;

function renderManifest(
  args: TemplateRenderArgs<WebhookInputs>,
): RenderedManifest {
  return {
    slug: args.slug,
    name: args.name,
    version: "1.0.0",
    description:
      args.description ??
      "Handles incoming HTTP webhook requests. Pair with an HTTP_ROUTE resource.",
    category: "automation",
    requiredGateways: [],
    tags: ["webhook", "http", "starter"],
    difficulty: "beginner",
    configSchema: {
      type: "object",
      properties: {
        defaultResponse: {
          type: "object",
          title: "Default response body",
          description:
            "Returned as JSON when the handler does not call ctx.respond().",
          default: args.inputs.defaultResponse,
        },
        logRequests: {
          type: "boolean",
          title: "Log requests",
          default: args.inputs.logRequests,
        },
      },
    },
    entryFile: "index.js",
    layout: "directory",
    icon: "webhook",
    author: "cursor-buildspec",
    isBuiltin: false,
    eventTypes: ["http.request"],
    eventRole: "responder",
    inputSchema: {
      type: "object",
      properties: {
        method: { type: "string" },
        path: { type: "string" },
        headers: { type: "object" },
        body: {},
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        status: { type: "number" },
        body: {},
      },
    },
  };
}

function renderEntry(args: TemplateRenderArgs<WebhookInputs>): string {
  const defaultResponse = JSON.stringify(args.inputs.defaultResponse);
  const logRequests = args.inputs.logRequests ? "true" : "false";

  return `// Auto-generated by cursor-buildspec template "webhook-handler-javascript".
// Plugin: ${args.slug}
//
// Hook signature: \`onHttpRequest(event, ctx)\` where:
//   event.method  — "GET" | "POST" | ...
//   event.path    — the matched URL path
//   event.headers — Record<string, string>
//   event.body    — parsed JSON body (or raw string if not JSON)
//   ctx.config    — your saved configuration (see plugin.json)
//   ctx.respond({ status, body }) — send a custom response
//   ctx.log.info / ctx.log.error  — host-provided logger
//
// If you do not call ctx.respond(...) the host returns the configured
// default response with status 200.

const DEFAULT_RESPONSE = ${defaultResponse};
const LOG_REQUESTS = ${logRequests};

module.exports.onHttpRequest = async function onHttpRequest(event, ctx) {
  const shouldLog = (ctx.config && ctx.config.logRequests === true) || LOG_REQUESTS;
  if (shouldLog && ctx.log && typeof ctx.log.info === "function") {
    ctx.log.info({ method: event.method, path: event.path }, "webhook received");
  }

  const responseBody = (ctx.config && ctx.config.defaultResponse) || DEFAULT_RESPONSE;

  if (typeof ctx.respond === "function") {
    ctx.respond({ status: 200, body: responseBody });
    return;
  }

  // Older host runtimes that expect a return value:
  return { status: 200, body: responseBody };
};
`;
}

function renderReadme(args: TemplateRenderArgs<WebhookInputs>): string {
  const defaults = JSON.stringify(args.inputs.defaultResponse);
  return `# ${args.name}

Auto-generated webhook handler.

**Slug:** \`${args.slug}\`

## What it does

Handles incoming HTTP requests routed to it via an \`HTTP_ROUTE\`
ProjectResource. Returns a configurable JSON body on success.

## Wiring

In your BuildSpec, point an \`HTTP_ROUTE\` resource at this plugin:

\`\`\`json
{
  "ref": "incoming",
  "kind": "HTTP_ROUTE",
  "name": "Incoming Webhook",
  "httpRoute": {
    "method": "POST",
    "path": "/webhooks/incoming",
    "targetPluginRef": "${args.slug}"
  }
}
\`\`\`

## Configuration

| Field             | Type    | Default                | Description                                |
| ----------------- | ------- | ---------------------- | ------------------------------------------ |
| \`defaultResponse\` | object  | \`${defaults}\` | Returned when the handler does not call \`ctx.respond\`. |
| \`logRequests\`     | boolean | \`${args.inputs.logRequests}\` | Log each request at info level.            |

## Files

- \`plugin.json\` — manifest
- \`index.js\` — entry point (\`onHttpRequest\` hook)
- \`README.md\` — this file

## Generated by

cursor-buildspec template \`webhook-handler-javascript\` v1.
`;
}

export const webhookHandlerJavascriptTemplate: CodeTemplate<WebhookInputs> = {
  id: "webhook-handler-javascript",
  displayName: "Webhook Handler (JavaScript)",
  description:
    "HTTP webhook handler. Pairs with an HTTP_ROUTE ProjectResource. Zero dependencies.",
  language: "javascript",
  requiredGateways: [],
  inputs,
  render(args: TemplateRenderArgs<WebhookInputs>): TemplateRenderResult {
    const manifest = renderManifest(args);
    const indexJs = renderEntry(args);
    const readme = renderReadme(args);

    return {
      manifest,
      slug: args.slug,
      entryFile: manifest.entryFile,
      files: [
        { path: "plugin.json", content: JSON.stringify(manifest, null, 2) + "\n" },
        { path: "index.js", content: indexJs },
        { path: "README.md", content: readme },
      ],
    };
  },
};
